# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1010, 523)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(578, 357))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sound_track_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.sound_track_label.setFont(font)
        self.sound_track_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sound_track_label.setObjectName("sound_track_label")
        self.gridLayout.addWidget(self.sound_track_label, 1, 0, 1, 1)
        self.source_time_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.source_time_label.setFont(font)
        self.source_time_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.source_time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.source_time_label.setObjectName("source_time_label")
        self.gridLayout.addWidget(self.source_time_label, 0, 0, 1, 1)
        self.sound_track_button = QtWidgets.QPushButton(self.centralwidget)
        self.sound_track_button.setObjectName("sound_track_button")
        self.gridLayout.addWidget(self.sound_track_button, 1, 2, 1, 1)
        self.source_time_tb = QtWidgets.QLineEdit(self.centralwidget)
        self.source_time_tb.setEnabled(True)
        self.source_time_tb.setInputMethodHints(QtCore.Qt.ImhNone)
        self.source_time_tb.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.source_time_tb.setObjectName("source_time_tb")
        self.gridLayout.addWidget(self.source_time_tb, 0, 1, 1, 1)
        self.sound_track_tb = QtWidgets.QLineEdit(self.centralwidget)
        self.sound_track_tb.setEnabled(True)
        self.sound_track_tb.setObjectName("sound_track_tb")
        self.gridLayout.addWidget(self.sound_track_tb, 1, 1, 1, 1)
        self.source_time_button = QtWidgets.QPushButton(self.centralwidget)
        self.source_time_button.setObjectName("source_time_button")
        self.gridLayout.addWidget(self.source_time_button, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_preview = QtWidgets.QVBoxLayout()
        self.frame_preview.setObjectName("frame_preview")
        self.preview_graphic = QtWidgets.QGraphicsView(self.centralwidget)
        self.preview_graphic.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.preview_graphic.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.preview_graphic.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.preview_graphic.setObjectName("preview_graphic")
        self.frame_preview.addWidget(self.preview_graphic)
        self.frame_controls = QtWidgets.QHBoxLayout()
        self.frame_controls.setObjectName("frame_controls")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.frame_controls.addItem(spacerItem)
        self.frame_previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.frame_previous_button.setObjectName("frame_previous_button")
        self.frame_controls.addWidget(self.frame_previous_button)
        self.refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_button.setObjectName("refresh_button")
        self.frame_controls.addWidget(self.refresh_button)
        self.frame_next_button = QtWidgets.QPushButton(self.centralwidget)
        self.frame_next_button.setObjectName("frame_next_button")
        self.frame_controls.addWidget(self.frame_next_button)
        self.play_preview_button = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_preview_button.sizePolicy().hasHeightForWidth())
        self.play_preview_button.setSizePolicy(sizePolicy)
        self.play_preview_button.setObjectName("play_preview_button")
        self.frame_controls.addWidget(self.play_preview_button)
        self.reset_preview_button = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_preview_button.sizePolicy().hasHeightForWidth())
        self.reset_preview_button.setSizePolicy(sizePolicy)
        self.reset_preview_button.setObjectName("reset_preview_button")
        self.frame_controls.addWidget(self.reset_preview_button)
        self.skip_to_end_button = QtWidgets.QToolButton(self.centralwidget)
        self.skip_to_end_button.setObjectName("skip_to_end_button")
        self.frame_controls.addWidget(self.skip_to_end_button)
        self.mute_preview_button = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mute_preview_button.sizePolicy().hasHeightForWidth())
        self.mute_preview_button.setSizePolicy(sizePolicy)
        self.mute_preview_button.setObjectName("mute_preview_button")
        self.frame_controls.addWidget(self.mute_preview_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.frame_controls.addItem(spacerItem1)
        self.frame_preview.addLayout(self.frame_controls)
        self.horizontalLayout_2.addLayout(self.frame_preview)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout10 = QtWidgets.QVBoxLayout()
        self.verticalLayout10.setObjectName("verticalLayout10")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.font_choice_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.font_choice_label.setFont(font)
        self.font_choice_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.font_choice_label.setObjectName("font_choice_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.font_choice_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.font_tb = QtWidgets.QLineEdit(self.centralwidget)
        self.font_tb.setEnabled(True)
        self.font_tb.setObjectName("font_tb")
        self.horizontalLayout_4.addWidget(self.font_tb)
        self.font_button = QtWidgets.QPushButton(self.centralwidget)
        self.font_button.setObjectName("font_button")
        self.horizontalLayout_4.addWidget(self.font_button)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout10.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.font_size_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.font_size_label.setFont(font)
        self.font_size_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.font_size_label.setObjectName("font_size_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.font_size_label)
        self.font_size_tb = QtWidgets.QSpinBox(self.centralwidget)
        self.font_size_tb.setMinimumSize(QtCore.QSize(70, 0))
        self.font_size_tb.setMinimum(1)
        self.font_size_tb.setMaximum(10000)
        self.font_size_tb.setSingleStep(1)
        self.font_size_tb.setObjectName("font_size_tb")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.font_size_tb)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.red_layout_2 = QtWidgets.QFormLayout()
        self.red_layout_2.setObjectName("red_layout_2")
        self.red_label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.red_label_2.setFont(font)
        self.red_label_2.setObjectName("red_label_2")
        self.red_layout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.red_label_2)
        self.red_spin_box_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.red_spin_box_2.setMaximum(255)
        self.red_spin_box_2.setObjectName("red_spin_box_2")
        self.red_layout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.red_spin_box_2)
        self.horizontalLayout.addLayout(self.red_layout_2)
        self.green_layout = QtWidgets.QFormLayout()
        self.green_layout.setObjectName("green_layout")
        self.green_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.green_label.setFont(font)
        self.green_label.setObjectName("green_label")
        self.green_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.green_label)
        self.green_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.green_spin_box.setMaximum(255)
        self.green_spin_box.setObjectName("green_spin_box")
        self.green_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.green_spin_box)
        self.horizontalLayout.addLayout(self.green_layout)
        self.blue_layout = QtWidgets.QFormLayout()
        self.blue_layout.setObjectName("blue_layout")
        self.blue_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.blue_label.setFont(font)
        self.blue_label.setObjectName("blue_label")
        self.blue_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.blue_label)
        self.blue_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.blue_spin_box.setMaximum(255)
        self.blue_spin_box.setObjectName("blue_spin_box")
        self.blue_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.blue_spin_box)
        self.horizontalLayout.addLayout(self.blue_layout)
        self.text_color_preview = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_color_preview.sizePolicy().hasHeightForWidth())
        self.text_color_preview.setSizePolicy(sizePolicy)
        self.text_color_preview.setMinimumSize(QtCore.QSize(19, 19))
        self.text_color_preview.setMaximumSize(QtCore.QSize(19, 19))
        self.text_color_preview.setBaseSize(QtCore.QSize(19, 19))
        self.text_color_preview.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_color_preview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_color_preview.setObjectName("text_color_preview")
        self.horizontalLayout.addWidget(self.text_color_preview)
        self.verticalLayout10.addLayout(self.horizontalLayout)
        self.textboxColorLayout = QtWidgets.QHBoxLayout()
        self.textboxColorLayout.setObjectName("textboxColorLayout")
        self.show_bounding_box = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.show_bounding_box.setFont(font)
        self.show_bounding_box.setObjectName("show_bounding_box")
        self.textboxColorLayout.addWidget(self.show_bounding_box)
        self.red_layout_text_box = QtWidgets.QFormLayout()
        self.red_layout_text_box.setObjectName("red_layout_text_box")
        self.red_label_text_box = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.red_label_text_box.setFont(font)
        self.red_label_text_box.setObjectName("red_label_text_box")
        self.red_layout_text_box.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.red_label_text_box)
        self.red_spin_box_text_box = QtWidgets.QSpinBox(self.centralwidget)
        self.red_spin_box_text_box.setMaximum(255)
        self.red_spin_box_text_box.setObjectName("red_spin_box_text_box")
        self.red_layout_text_box.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.red_spin_box_text_box)
        self.textboxColorLayout.addLayout(self.red_layout_text_box)
        self.green_layout_text_box = QtWidgets.QFormLayout()
        self.green_layout_text_box.setObjectName("green_layout_text_box")
        self.green_label_text_box = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.green_label_text_box.setFont(font)
        self.green_label_text_box.setObjectName("green_label_text_box")
        self.green_layout_text_box.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.green_label_text_box)
        self.green_spin_box_text_box = QtWidgets.QSpinBox(self.centralwidget)
        self.green_spin_box_text_box.setMaximum(255)
        self.green_spin_box_text_box.setObjectName("green_spin_box_text_box")
        self.green_layout_text_box.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.green_spin_box_text_box)
        self.textboxColorLayout.addLayout(self.green_layout_text_box)
        self.blue_layout_text_box = QtWidgets.QFormLayout()
        self.blue_layout_text_box.setObjectName("blue_layout_text_box")
        self.blue_label_text_box = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.blue_label_text_box.setFont(font)
        self.blue_label_text_box.setObjectName("blue_label_text_box")
        self.blue_layout_text_box.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.blue_label_text_box)
        self.blue_spin_box_text_box = QtWidgets.QSpinBox(self.centralwidget)
        self.blue_spin_box_text_box.setMaximum(255)
        self.blue_spin_box_text_box.setObjectName("blue_spin_box_text_box")
        self.blue_layout_text_box.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.blue_spin_box_text_box)
        self.textboxColorLayout.addLayout(self.blue_layout_text_box)
        self.text_box_color_preview = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_box_color_preview.sizePolicy().hasHeightForWidth())
        self.text_box_color_preview.setSizePolicy(sizePolicy)
        self.text_box_color_preview.setMinimumSize(QtCore.QSize(19, 19))
        self.text_box_color_preview.setMaximumSize(QtCore.QSize(19, 19))
        self.text_box_color_preview.setBaseSize(QtCore.QSize(19, 19))
        self.text_box_color_preview.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_box_color_preview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_box_color_preview.setObjectName("text_box_color_preview")
        self.textboxColorLayout.addWidget(self.text_box_color_preview)
        self.verticalLayout10.addLayout(self.textboxColorLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout10)
        self.VerticalLayout12 = QtWidgets.QVBoxLayout()
        self.VerticalLayout12.setObjectName("VerticalLayout12")
        self.align_text_top_radial = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.align_text_top_radial.setFont(font)
        self.align_text_top_radial.setObjectName("align_text_top_radial")
        self.VerticalLayout12.addWidget(self.align_text_top_radial)
        self.align_text_center_radial = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.align_text_center_radial.setFont(font)
        self.align_text_center_radial.setChecked(True)
        self.align_text_center_radial.setObjectName("align_text_center_radial")
        self.VerticalLayout12.addWidget(self.align_text_center_radial)
        self.align_text_bottom_radial = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.align_text_bottom_radial.setFont(font)
        self.align_text_bottom_radial.setObjectName("align_text_bottom_radial")
        self.VerticalLayout12.addWidget(self.align_text_bottom_radial)
        self.horizontalLayout_3.addLayout(self.VerticalLayout12)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.background_preview = QtWidgets.QGraphicsView(self.centralwidget)
        self.background_preview.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.background_preview.setInputMethodHints(QtCore.Qt.ImhNone)
        self.background_preview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_preview.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.background_preview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.background_preview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.background_preview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.background_preview.setObjectName("background_preview")
        self.verticalLayout_2.addWidget(self.background_preview)
        self.background_button = QtWidgets.QPushButton(self.centralwidget)
        self.background_button.setObjectName("background_button")
        self.verticalLayout_2.addWidget(self.background_button)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.video_location_button = QtWidgets.QPushButton(self.centralwidget)
        self.video_location_button.setObjectName("video_location_button")
        self.gridLayout_2.addWidget(self.video_location_button, 0, 2, 1, 1)
        self.video_location_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.video_location_label.setFont(font)
        self.video_location_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_location_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.video_location_label.setObjectName("video_location_label")
        self.gridLayout_2.addWidget(self.video_location_label, 0, 0, 1, 1)
        self.video_location_tb = QtWidgets.QLineEdit(self.centralwidget)
        self.video_location_tb.setEnabled(True)
        self.video_location_tb.setObjectName("video_location_tb")
        self.gridLayout_2.addWidget(self.video_location_tb, 0, 1, 1, 1)
        self.generate_video_button = QtWidgets.QPushButton(self.centralwidget)
        self.generate_video_button.setObjectName("generate_video_button")
        self.gridLayout_2.addWidget(self.generate_video_button, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.video_generation_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.video_generation_progress.setEnabled(True)
        self.video_generation_progress.setProperty("value", 0)
        self.video_generation_progress.setInvertedAppearance(False)
        self.video_generation_progress.setObjectName("video_generation_progress")
        self.verticalLayout_3.addWidget(self.video_generation_progress)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 22))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.actionOpenRecent = QtWidgets.QMenu(self.menuFile)
        self.actionOpenRecent.setObjectName("actionOpenRecent")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuTheme = QtWidgets.QMenu(self.menuOptions)
        self.menuTheme.setObjectName("menuTheme")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("open")
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setCheckable(False)
        self.actionNew.setChecked(False)
        self.actionNew.setObjectName("actionNew")
        self.actionConfigure_FFMPEG_location = QtWidgets.QAction(MainWindow)
        self.actionConfigure_FFMPEG_location.setObjectName("actionConfigure_FFMPEG_location")
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClear_all_settings = QtWidgets.QAction(MainWindow)
        self.actionClear_all_settings.setObjectName("actionClear_all_settings")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpenRecent.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuOptions.addAction(self.actionConfigure_FFMPEG_location)
        self.menuOptions.addAction(self.menuTheme.menuAction())
        self.menuOptions.addAction(self.actionClear_all_settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.source_time_tb, self.source_time_button)
        MainWindow.setTabOrder(self.source_time_button, self.sound_track_tb)
        MainWindow.setTabOrder(self.sound_track_tb, self.sound_track_button)
        MainWindow.setTabOrder(self.sound_track_button, self.preview_graphic)
        MainWindow.setTabOrder(self.preview_graphic, self.font_tb)
        MainWindow.setTabOrder(self.font_tb, self.font_button)
        MainWindow.setTabOrder(self.font_button, self.font_size_tb)
        MainWindow.setTabOrder(self.font_size_tb, self.red_spin_box_2)
        MainWindow.setTabOrder(self.red_spin_box_2, self.green_spin_box)
        MainWindow.setTabOrder(self.green_spin_box, self.blue_spin_box)
        MainWindow.setTabOrder(self.blue_spin_box, self.text_color_preview)
        MainWindow.setTabOrder(self.text_color_preview, self.background_preview)
        MainWindow.setTabOrder(self.background_preview, self.frame_previous_button)
        MainWindow.setTabOrder(self.frame_previous_button, self.refresh_button)
        MainWindow.setTabOrder(self.refresh_button, self.frame_next_button)
        MainWindow.setTabOrder(self.frame_next_button, self.background_button)
        MainWindow.setTabOrder(self.background_button, self.video_location_tb)
        MainWindow.setTabOrder(self.video_location_tb, self.video_location_button)
        MainWindow.setTabOrder(self.video_location_button, self.generate_video_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SubVideo"))
        self.sound_track_label.setText(_translate("MainWindow", "Sound Track:"))
        self.source_time_label.setText(_translate("MainWindow", "Source Time:"))
        self.sound_track_button.setToolTip(_translate("MainWindow", "Browse Soundtrack (Ctrl+T)"))
        self.sound_track_button.setStatusTip(_translate("MainWindow", "Browse for sound track file"))
        self.sound_track_button.setText(_translate("MainWindow", "Browse"))
        self.sound_track_button.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.source_time_button.setToolTip(_translate("MainWindow", "Browse Source Time File (Ctrl+E)"))
        self.source_time_button.setStatusTip(_translate("MainWindow", "Browse for frame text and timecode file"))
        self.source_time_button.setText(_translate("MainWindow", "Browse"))
        self.source_time_button.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.preview_graphic.setStatusTip(_translate("MainWindow", "(Click for larger preview) Preview window for each frame"))
        self.frame_previous_button.setToolTip(_translate("MainWindow", "Show previous frame (Ctrl+p)"))
        self.frame_previous_button.setStatusTip(_translate("MainWindow", "Show previous frame"))
        self.frame_previous_button.setText(_translate("MainWindow", "Previous"))
        self.frame_previous_button.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.refresh_button.setToolTip(_translate("MainWindow", "Refresh Preview (Ctrl+R)"))
        self.refresh_button.setStatusTip(_translate("MainWindow", "Refresh frame preview window"))
        self.refresh_button.setText(_translate("MainWindow", "Refresh"))
        self.refresh_button.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.frame_next_button.setToolTip(_translate("MainWindow", "Show next frame (Ctrl+N)"))
        self.frame_next_button.setStatusTip(_translate("MainWindow", "Show next frame"))
        self.frame_next_button.setText(_translate("MainWindow", "Next"))
        self.frame_next_button.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.play_preview_button.setToolTip(_translate("MainWindow", "Play Preview (Shift+P)"))
        self.play_preview_button.setStatusTip(_translate("MainWindow", "Play Preview"))
        self.play_preview_button.setText(_translate("MainWindow", "..."))
        self.play_preview_button.setShortcut(_translate("MainWindow", "Shift+P"))
        self.reset_preview_button.setToolTip(_translate("MainWindow", "Reset Preview (Ctrl+Shift+R)"))
        self.reset_preview_button.setStatusTip(_translate("MainWindow", "Reset Preview"))
        self.reset_preview_button.setText(_translate("MainWindow", "↻"))
        self.reset_preview_button.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.skip_to_end_button.setToolTip(_translate("MainWindow", "Skip to End (Ctrl+Shift+E)"))
        self.skip_to_end_button.setStatusTip(_translate("MainWindow", "Skip to End"))
        self.skip_to_end_button.setText(_translate("MainWindow", "..."))
        self.skip_to_end_button.setShortcut(_translate("MainWindow", "Ctrl+Shift+E"))
        self.mute_preview_button.setToolTip(_translate("MainWindow", "Mute Preview (Ctrl+M)"))
        self.mute_preview_button.setStatusTip(_translate("MainWindow", "Mute Preview"))
        self.mute_preview_button.setText(_translate("MainWindow", "..."))
        self.mute_preview_button.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.font_choice_label.setText(_translate("MainWindow", "Font:"))
        self.font_button.setToolTip(_translate("MainWindow", "Browse for font file (Ctrl+F)"))
        self.font_button.setStatusTip(_translate("MainWindow", "Browse for font file"))
        self.font_button.setText(_translate("MainWindow", "Browse"))
        self.font_button.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.font_size_label.setText(_translate("MainWindow", "Font Size:"))
        self.font_size_tb.setStatusTip(_translate("MainWindow", "Set font size"))
        self.red_label_2.setText(_translate("MainWindow", "R"))
        self.red_spin_box_2.setStatusTip(_translate("MainWindow", "Set font red value"))
        self.green_label.setText(_translate("MainWindow", "G"))
        self.green_spin_box.setStatusTip(_translate("MainWindow", "Set font green value"))
        self.blue_label.setText(_translate("MainWindow", "B"))
        self.blue_spin_box.setStatusTip(_translate("MainWindow", "Set font blue value"))
        self.show_bounding_box.setStatusTip(_translate("MainWindow", "Show box around text"))
        self.show_bounding_box.setText(_translate("MainWindow", "Show bounding box"))
        self.red_label_text_box.setText(_translate("MainWindow", "R"))
        self.red_spin_box_text_box.setStatusTip(_translate("MainWindow", "Set font red value"))
        self.green_label_text_box.setText(_translate("MainWindow", "G"))
        self.green_spin_box_text_box.setStatusTip(_translate("MainWindow", "Set font green value"))
        self.blue_label_text_box.setText(_translate("MainWindow", "B"))
        self.blue_spin_box_text_box.setStatusTip(_translate("MainWindow", "Set font blue value"))
        self.align_text_top_radial.setStatusTip(_translate("MainWindow", "Align text to top of screen"))
        self.align_text_top_radial.setText(_translate("MainWindow", "Top"))
        self.align_text_center_radial.setStatusTip(_translate("MainWindow", "Align text to center of screen"))
        self.align_text_center_radial.setText(_translate("MainWindow", "Center"))
        self.align_text_bottom_radial.setStatusTip(_translate("MainWindow", "Align text to bottom of screen"))
        self.align_text_bottom_radial.setText(_translate("MainWindow", "Bottom"))
        self.background_preview.setStatusTip(_translate("MainWindow", "Preview window showing the background frame"))
        self.background_button.setToolTip(_translate("MainWindow", "Browse for background frame (Ctrl+B)"))
        self.background_button.setStatusTip(_translate("MainWindow", "Browse for background frame"))
        self.background_button.setText(_translate("MainWindow", "Select Background Frame"))
        self.background_button.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.video_location_button.setToolTip(_translate("MainWindow", "Browse for output file location (Ctrl+L)"))
        self.video_location_button.setStatusTip(_translate("MainWindow", "Browse for output video location"))
        self.video_location_button.setText(_translate("MainWindow", "Browse"))
        self.video_location_button.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.video_location_label.setText(_translate("MainWindow", "Save As:"))
        self.generate_video_button.setToolTip(_translate("MainWindow", "Generate Video (Ctrl+Return)"))
        self.generate_video_button.setStatusTip(_translate("MainWindow", "Generate video"))
        self.generate_video_button.setText(_translate("MainWindow", "Generate Video"))
        self.generate_video_button.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpenRecent.setTitle(_translate("MainWindow", "Open Recent"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setShortcut(_translate("MainWindow", "Esc"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionConfigure_FFMPEG_location.setText(_translate("MainWindow", "Congiure FFMPEG location"))
        self.actionConfigure_FFMPEG_location.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Shift+Q"))
        self.actionClear_all_settings.setText(_translate("MainWindow", "Clear all settings"))
import main_images_rc
