# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_ffmpeg_executable.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FfmpegExecDialog(object):
    def setupUi(self, FfmpegExecDialog):
        FfmpegExecDialog.setObjectName("FfmpegExecDialog")
        FfmpegExecDialog.resize(555, 245)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FfmpegExecDialog.sizePolicy().hasHeightForWidth())
        FfmpegExecDialog.setSizePolicy(sizePolicy)
        FfmpegExecDialog.setWindowOpacity(1.0)
        FfmpegExecDialog.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(FfmpegExecDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.search_info_rtlabel = QtWidgets.QLabel(FfmpegExecDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_info_rtlabel.sizePolicy().hasHeightForWidth())
        self.search_info_rtlabel.setSizePolicy(sizePolicy)
        self.search_info_rtlabel.setTextFormat(QtCore.Qt.RichText)
        self.search_info_rtlabel.setScaledContents(False)
        self.search_info_rtlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.search_info_rtlabel.setWordWrap(True)
        self.search_info_rtlabel.setOpenExternalLinks(True)
        self.search_info_rtlabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.search_info_rtlabel.setObjectName("search_info_rtlabel")
        self.verticalLayout_4.addWidget(self.search_info_rtlabel)
        self.ffmpeg_exec_grid = QtWidgets.QGridLayout()
        self.ffmpeg_exec_grid.setObjectName("ffmpeg_exec_grid")
        self.ffmpeg_exec_button = QtWidgets.QPushButton(FfmpegExecDialog)
        self.ffmpeg_exec_button.setObjectName("ffmpeg_exec_button")
        self.ffmpeg_exec_grid.addWidget(self.ffmpeg_exec_button, 0, 2, 1, 1)
        self.ffmpeg_exec_tb = QtWidgets.QLineEdit(FfmpegExecDialog)
        self.ffmpeg_exec_tb.setEnabled(True)
        self.ffmpeg_exec_tb.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ffmpeg_exec_tb.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ffmpeg_exec_tb.setObjectName("ffmpeg_exec_tb")
        self.ffmpeg_exec_grid.addWidget(self.ffmpeg_exec_tb, 0, 1, 1, 1)
        self.ffmpeg_exec_label = QtWidgets.QLabel(FfmpegExecDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.ffmpeg_exec_label.setFont(font)
        self.ffmpeg_exec_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ffmpeg_exec_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ffmpeg_exec_label.setObjectName("ffmpeg_exec_label")
        self.ffmpeg_exec_grid.addWidget(self.ffmpeg_exec_label, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.ffmpeg_exec_grid)
        self.save_version_grid = QtWidgets.QGridLayout()
        self.save_version_grid.setObjectName("save_version_grid")
        self.ffmpeg_version_label = QtWidgets.QLabel(FfmpegExecDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ffmpeg_version_label.sizePolicy().hasHeightForWidth())
        self.ffmpeg_version_label.setSizePolicy(sizePolicy)
        self.ffmpeg_version_label.setObjectName("ffmpeg_version_label")
        self.save_version_grid.addWidget(self.ffmpeg_version_label, 0, 0, 1, 1)
        self.verify_button = QtWidgets.QPushButton(FfmpegExecDialog)
        self.verify_button.setObjectName("verify_button")
        self.save_version_grid.addWidget(self.verify_button, 0, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(FfmpegExecDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setObjectName("save_button")
        self.save_version_grid.addWidget(self.save_button, 0, 2, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(FfmpegExecDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.save_version_grid.addWidget(self.cancel_button, 0, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.save_version_grid)
        self.verticalLayout_4.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(FfmpegExecDialog)
        QtCore.QMetaObject.connectSlotsByName(FfmpegExecDialog)

    def retranslateUi(self, FfmpegExecDialog):
        _translate = QtCore.QCoreApplication.translate
        FfmpegExecDialog.setWindowTitle(_translate("FfmpegExecDialog", "Search for FFMPEG Executable"))
        self.search_info_rtlabel.setText(_translate("FfmpegExecDialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Search for FFMPEG Executable</span></p><p><span style=\" font-size:9pt;\">You are seeing this dialog because either you would like to use a custom FFMPEG executable (i.e. not the one found in your path) or you do not have FFMPEG in your path.</span></p><p><span style=\" font-size:9pt;\">Either use the browse button to select the FFMPEG executable, or type the commandline name into the text box. Then, verify the FFMPEG version and save.</span></p><p><span style=\" font-size:9pt;\">FFMPEG is required to use this application, and is not included. You can learn more about FFMPEG and download it here: </span><a href=\"https://www.ffmpeg.org/download.html\"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">https://www.ffmpeg.org/download.html</span></a></p></body></html>"))
        self.ffmpeg_exec_button.setToolTip(_translate("FfmpegExecDialog", "Browse Source Time File (Ctrl+E)"))
        self.ffmpeg_exec_button.setStatusTip(_translate("FfmpegExecDialog", "Browse for frame text and timecode file"))
        self.ffmpeg_exec_button.setText(_translate("FfmpegExecDialog", "Browse"))
        self.ffmpeg_exec_button.setShortcut(_translate("FfmpegExecDialog", "Ctrl+E"))
        self.ffmpeg_exec_label.setText(_translate("FfmpegExecDialog", " ffmpeg executable:"))
        self.ffmpeg_version_label.setText(_translate("FfmpegExecDialog", "Found FFMPEG version X.X.X"))
        self.verify_button.setText(_translate("FfmpegExecDialog", "Verify"))
        self.save_button.setText(_translate("FfmpegExecDialog", "Save"))
        self.cancel_button.setText(_translate("FfmpegExecDialog", "Cancel"))
